#include <stdbool.h> // bool
#include <stdio.h> // snprintf
#include "../tests.h"
#include "../../pwasm.h"
#include "../../pwasm-compile.h"

// maximum test stack depth
#define MAX_STACK_DEPTH 100

// add-two.wasm: one function to test integer addition
// generated by: xxd -c 8 -i data/wat/17-add-two.wasm
// (source: data/wat/17-add-two.wat)
static const uint8_t ADD_TWO_WASM[] = {
  0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
  0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, 0x03,
  0x02, 0x01, 0x00, 0x07, 0x0b, 0x01, 0x07, 0x61,
  0x64, 0x64, 0x5f, 0x74, 0x77, 0x6f, 0x00, 0x00,
  0x0a, 0x0b, 0x01, 0x09, 0x00, 0x41, 0xfb, 0x00,
  0x41, 0xc8, 0x03, 0x6a, 0x0b
};

void test_compile(
  cli_test_ctx_t * const test_ctx,
  const cli_test_t * const cli_test
) {
  // create a memory context
  pwasm_mem_ctx_t mem_ctx = pwasm_mem_ctx_init_defaults(NULL);

  // set up stack
  pwasm_val_t stack_vals[MAX_STACK_DEPTH];
  pwasm_stack_t stack = {
    .ptr = stack_vals,
    .len = MAX_STACK_DEPTH,
  };

  // get interpreter callbacks
  pwasm_env_cbs_t cbs;
  pwasm_aot_jit_get_cbs(&cbs, pwasm_compile);

  // create environment, check for error
  pwasm_env_t env;
  if (!pwasm_env_init(&env, &mem_ctx, &cbs, &stack, NULL)) {
    cli_test_error(test_ctx, "pwasm_env_init() failed");
    return;
  }

  // build buffer
  const pwasm_buf_t buf = { ADD_TWO_WASM, sizeof(ADD_TWO_WASM) };

  // parse mod, check for error
  pwasm_mod_t mod;
  if (!pwasm_mod_init(&mem_ctx, &mod, buf)) {
    cli_test_error(test_ctx, "pwasm_mod_init() failed");
    return;
  }

  // add mod to env, check for error
  if (!pwasm_env_add_mod(&env, "add-two", &mod)) {
    cli_test_error(test_ctx, "pwasm_env_add_mod() failed");
    return;
  }

  // call func
  const bool call_ok = pwasm_call(&env, "add-two", "add_two");
  if (call_ok) {
    cli_test_pass(test_ctx, cli_test, "pwasm_call()");
  } else {
    cli_test_fail(test_ctx, cli_test, "pwasm_call() failed");
  }

  if (call_ok && (stack.pos == 1)) {
    cli_test_pass(test_ctx, cli_test, "env.stack == 1");
  } else {
    char buf[512];
    snprintf(buf, sizeof(buf), "stack.pos: got %zu, expected %u", stack.pos, 1);
    cli_test_fail(test_ctx, cli_test, buf);
  }

  if (call_ok && (stack.pos == 1) && (stack.ptr[0].i32 == 579)) {
    cli_test_pass(test_ctx, cli_test, "stack.ptr[0] == 579");
  } else {
    char buf[512];
    snprintf(buf, sizeof(buf), "stack.ptr[0]: got %u, expected %u", stack.ptr[0].i32, 579);
    cli_test_fail(test_ctx, cli_test, buf);
  }
}
